package me.mtrupkin.console

/**
 * Created by mtrupkin on 12/14/2014.
 */
object Key extends Enumeration {
  type Key = Value

  val DIGIT0 = Value("DIGIT0")
  val DIGIT1 = Value("DIGIT1")
  val DIGIT2 = Value("DIGIT2")
  val DIGIT3 = Value("DIGIT3")
  val DIGIT4 = Value("DIGIT4")
  val DIGIT5 = Value("DIGIT5")
  val DIGIT6 = Value("DIGIT6")
  val DIGIT7 = Value("DIGIT7")
  val DIGIT8 = Value("DIGIT8")
  val DIGIT9 = Value("DIGIT9")

  val A = Value("A")
  val B = Value("B")
  val C = Value("C")
  val D = Value("D")
  val E = Value("E")
  val F = Value("F")
  val G = Value("G")
  val H = Value("H")
  val I = Value("I")
  val J = Value("J")
  val K = Value("K")
  val L = Value("L")
  val M = Value("M")
  val N = Value("N")
  val O = Value("O")
  val P = Value("P")
  val Q = Value("Q")
  val R = Value("R")
  val S = Value("S")
  val T = Value("T")
  val U = Value("U")
  val V = Value("V")
  val W = Value("W")
  val X = Value("X")
  val Y = Value("Y")
  val Z = Value("Z")

  val F1 = Value("F1")
  val F2 = Value("F2")
  val F3 = Value("F3")
  val F4 = Value("F4")
  val F5 = Value("F5")
  val F6 = Value("F6")
  val F7 = Value("F7")
  val F8 = Value("F8")
  val F9 = Value("F9")
  val F10 = Value("F10")
  val F11 = Value("F11")
  val F12 = Value("F12")
  val F13 = Value("F13")
  val F14 = Value("F14")
  val F15 = Value("F15")
  val F16 = Value("F16")
  val F17 = Value("F17")
  val F18 = Value("F18")
  val F19 = Value("F19")
  val F20 = Value("F20")
  val F21 = Value("F21")
  val F22 = Value("F22")
  val F23 = Value("F23")
  val F24 = Value("F24")

  val Enter = Value("Enter")
  val Backspace = Value("Backspace")
  val Tab = Value("Tab")
  val Cancel = Value("Cancel")
  val Clear = Value("Clear")
  val Shift = Value("Shift")
  val Ctrl = Value("Ctrl")
  val Alt = Value("Alt")
  val Pause = Value("Pause")
  val Caps_Lock = Value("Caps Lock")
  val Esc = Value("Esc")
  val Space = Value("Space")
  val Page_Up = Value("Page Up")
  val Page_Down = Value("Page Down")
  val End = Value("End")
  val Home = Value("Home")
  val Left = Value("Left")
  val Up = Value("Up")
  val Right = Value("Right")
  val Down = Value("Down")
  val Comma = Value("Comma")
  val Minus = Value("Minus")
  val Period = Value("Period")
  val Slash = Value("Slash")

  val Less = Value("Less")
  val Greater = Value("Greater")
}
